---
  # These constants are in use in PandaPose.py File, to set global sleep time and frequency
  static_sleep_time: 2
  zero_g_poses: 20
  dynamic_frequency: 100.0
  gravity_constant: 9.81
  oscillation_magnitude:
    - 0.75
    - 0.25
    - 0.35
    - 0.55
    - 0.75
    - 0.9
    - 0.9

    # - 1
    # - 0.5
    # - 0.6
    # - 0.8
    # - 0.1
    # - 1.2
    # - 1.2

    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5

  oscillation_frequency:
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0

    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5
    # - 1.5

    # - 1.1
    # - 0.5
    # - 0.65
    # - 0.8
    # - 0.8
    # - 1.15
    # - 1.15

  oscillation_time: 3.0
