---
  # These constants are in use in PandaPose.py File, to set global sleep time and frequency
  static_sleep_time: 2
  zero_g_poses: 16
  dynamic_frequency: 30.0
  gravity_constant: 9.81
  oscillation_magnitude: 2.0
  oscillation_frequency: 2.0
