---
  # These constants are used by publishers. They can be used to set ROS environment variables
  # This is just a sample. You should make your own publisher_variables.yaml and then put it in this directory
  # For publisher variables to work. Please make sure you don't repeat these variables across sample files. It's also
  # preferable to add some variables to existing files rather creating a new ones
  # With great power comes great responsibility
  "imu_number": 0,
  "GRAVITATIONAL_CONSTANT": 9.819,
  "RPi_bus_num": 1,
  "ros_core_ip": "192.168.50.118",
  "ros_core_port": 11311,
  "RPi_IP": "192.168.50.31"