<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="proximity">

    <xacro:macro name="proximity" params="proximity_id:='0' radius:=0.2 theta:=0.0 z0:=0 type:='fixed' freq:='100' connected_to:='' x0:=0.0 y0:=0.0">
        <!-- Connect proximity sensor to ${connected_to} -->
        <joint name="proximity${proximity_id}_to_${connected_to}" type="${type}">
            <parent link="${connected_to}"/>
            <child link="proximity_link${proximity_id}"/>
            <origin xyz="${x0+radius*sin(theta)} ${y0+radius*cos(theta)} ${z0}" rpy=" 0 0 ${pi/2 -theta}" />
        </joint>

        <!-- Box that represents sensor -->
        <link name="proximity_link${proximity_id}">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.01" rpy="0 0 0"/>
                <geometry>
                    <box size="0.01 0.03 0.03"/>
                </geometry>
            </visual>
        </link>

        <gazebo reference="proximity_link${proximity_id}">
            <material>Gazebo/YellowGlow</material>
            <sensor type="ray" name="proximity_sensor${proximity_id}">
                <pose>0 0 0 0 0 0</pose>
                <visualize>true</visualize>
                <update_rate>${freq}</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>1</samples>
                            <resolution>1</resolution>
                            <min_angle>-0.01</min_angle>
                            <max_angle>0.01</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.02</min>
                        <max>2.0</max>
                        <resolution>0.01</resolution>
                    </range>
                </ray>
                <plugin filename="libgazebo_ros_laser.so" name="proximity_plugin${proximity_id}">
                    <topicName>proximity_data${proximity_id}</topicName>
                    <bodyName>proximity_link${proximity_id}</bodyName>
                    <updateRateHZ>${freq}</updateRateHZ>
                    <gaussianNoise>0.0</gaussianNoise>
                    <xyzOffset>0.0 0.0 0.0</xyzOffset>
                    <rpyOffset>0 0 0</rpyOffset>
                    <frameName>proximity_link${proximity_id}</frameName>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>