name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: pip install -r requirements.txt
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
