name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: sudo apt-get install flake8
    - name: Run a multi-line script
      run: |
        flake8 --ignore=F841
        echo test, and deploy your project.
